# Generated by Django 6.1.1 on 2026-09-04 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('distributor', 'Distributor'), ('admin', 'Admin / Super Admin')], default='distributor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must contain 9 to 15 digits, optionally starting with '+'.", regex='^\\+?\\d{9,15}$')])),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must contain 9 to 15 digits, optionally starting with '+'.", regex='^\\+?\\d{9,15}$')])),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid pincode/ZIP (4 to 10 digits).', regex='^\\d{4,10}$')])),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST / Tax Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(help_text='The distributor who owns this customer record.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['status'], name='customers_status_47bd31_idx')],
            },
        ),
    ]
